name: 'Maven Deploy Central'
description: 'Deploy java package to Maven central'
inputs:
  NEXUS_MAVEN_REPO:
    default: unused
    required: true
  NEXUS_USERNAME:
    default: unused
    required: true
  NEXUS_PASSWORD:
    default: unused
    required: true
  ZEPBEN_GPG_KEY:
    description: "GPG key ID"
    required: true
  OSSRH_USERNAME:
    description: "Maven central username"
    required: true
  OSSRH_PASSWORD:
    description: "Maven central password"
    required: true
  GPG_KEY_ID:
    description: "Zepben GPG key ID"
    required: true
  GPG_KEY_PASSWORD:
    description: "Zepben GPG key password"
    required: true
  POM_PATH:
    description: "Path to pom.xml"
    required: true
    default: pom.xml

runs:
  using: "composite"
  steps: 
    - run: |
        echo "$ZEPBEN_GPG_KEY" | base64 -d > zepben-gpg.key
        gpg2 --batch --import zepben-gpg.key
        mvn clean deploy -f $POM_PATH -P release,ossrh -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dossrh.server.username=$OSSRH_USERNAME -Dossrh.server.password=$OSSRH_PASSWORD -Dgpg.key.id=$GPG_KEY_ID -Dgpg.key.password=$GPG_KEY_PASSWORD
      shell: bash
      env:
        NEXUS_MAVEN_REPO: ${{ inputs.NEXUS_MAVEN_REPO }}
        NEXUS_USERNAME: ${{ inputs.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ inputs.NEXUS_PASSWORD }}
        ZEPBEN_GPG_KEY: ${{ inputs.ZEPBEN_GPG_KEY }}
        OSSRH_USERNAME: ${{ inputs.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ inputs.OSSRH_PASSWORD }}
        GPG_KEY_ID: ${{ inputs.GPG_KEY_ID }}
        GPG_KEY_PASSWORD: ${{ inputs.GPG_KEY_PASSWORD }}
        POM_PATH: ${{ inputs.POM_PATH }}
