name: 'Maven Deploy Central'
description: 'Deploy java package to Maven central'
inputs:
  NEXUS_MAVEN_REPO:
    default: unused
    required: true
  NEXUS_USERNAME:
    default: unused
    required: true
  NEXUS_PASSWORD:
    default: unused
    required: true
  NEXUS_RELEASE_URL:
    default: unused
    required: true
  NEXUS_SNAPSHOT_URL:
    default: unused
    required: true
  ZEPBEN_GPG_KEY:
    description: "GPG key ID"
    default: unused
    required: true
  OSSRH_USERNAME:
    description: "Maven central username"
    default: unused
    required: true
  OSSRH_PASSWORD:
    description: "Maven central password"
    default: unused
    required: true
  GPG_KEY_ID:
    description: "Zepben GPG key ID"
    default: unused
    required: true
  GPG_KEY_PASSWORD:
    description: "Zepben GPG key password"
    default: unused
    required: true
  POM_PATH:
    description: "Path to pom.xml"
    required: true
    default: pom.xml
  PROFILE:
    description: "Maven profile"
    required: true
    default: ossrh
  SETTINGS_PATH:
    description: "Path to maven settings.xml"
    required: false

outputs:
  artifact:
    description: "The name of the artifact that is output"
    value: ${{ steps.deploy.outputs.artifact }}
  artifact-path:
    description: "The path to the artifact"
    value: ${{ steps.deploy.outputs.artifact-path }}
  version:
    description: "The version of the arfifact"
    value: ${{ steps.deploy.outputs.version }}
runs:
  using: "composite"
  steps: 
    - name: Deploy to maven central
      id: deploy
      run: |
        if [ "$PROFILE" = "ossrh" ]
        then
          echo "$ZEPBEN_GPG_KEY" | base64 -d > zepben-gpg.key
          gpg2 --batch --import zepben-gpg.key
          if [ -z $SETTINGS_PATH ]
          then
            mvn clean deploy -f $POM_PATH -P 'release,ossrh,!zepben-maven' -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dossrh.server.username=$OSSRH_USERNAME -Dossrh.server.password=$OSSRH_PASSWORD -Dgpg.key.id=$GPG_KEY_ID -Dgpg.key.password=$GPG_KEY_PASSWORD
          else
            mvn clean deploy -f $POM_PATH -P 'release,ossrh,!zepben-maven' -s $SETTINGS_PATH -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dossrh.server.username=$OSSRH_USERNAME -Dossrh.server.password=$OSSRH_PASSWORD -Dgpg.key.id=$GPG_KEY_ID -Dgpg.key.password=$GPG_KEY_PASSWORD
          fi
        elif [ "$PROFILE" = "zepben-maven" ]
        then
          if [ -z $SETTINGS_PATH ]
          then
            mvn clean deploy -f $POM_PATH -P 'zepben-maven' -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dserver.release.url=$NEXUS_RELEASE_URL -Dserver.snapshot.url=$NEXUS_SNAPSHOT_URL
          else
            mvn clean deploy -f $POM_PATH -P 'zepben-maven' -s $SETTINGS_PATH -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dserver.release.url=$NEXUS_RELEASE_URL -Dserver.snapshot.url=$NEXUS_SNAPSHOT_URL
          fi
        fi
        artifactId=$(xmlstarlet pyx $POM_PATH | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/artifactId")
        version=$(xmlstarlet pyx $POM_PATH | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/version")
        artifact="${artifactId}-${version}.jar"
        echo "::set-output name=artifact::$(echo $artifact)"
        echo "::set-output name=artifact-path::$(echo $(dirname $POM_PATH)/target/$artifact)"
        echo "::set-output name=version::$(echo $version)"
      shell: bash
      env:
        NEXUS_MAVEN_REPO: ${{ inputs.NEXUS_MAVEN_REPO }}
        NEXUS_USERNAME: ${{ inputs.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ inputs.NEXUS_PASSWORD }}
        NEXUS_RELEASE_URL: ${{ inputs.NEXUS_RELEASE_URL }}
        NEXUS_SNAPSHOT_URL: ${{ inputs.NEXUS_SNAPSHOT_URL }}
        ZEPBEN_GPG_KEY: ${{ inputs.ZEPBEN_GPG_KEY }}
        OSSRH_USERNAME: ${{ inputs.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ inputs.OSSRH_PASSWORD }}
        GPG_KEY_ID: ${{ inputs.GPG_KEY_ID }}
        GPG_KEY_PASSWORD: ${{ inputs.GPG_KEY_PASSWORD }}
        POM_PATH: ${{ inputs.POM_PATH }}
        PROFILE: ${{ inputs.PROFILE }}
        SETTINGS_PATH: ${{ inputs.SETTINGS_PATH }}
