name: 'Maven Deploy Central'
description: 'Deploy java package to Maven Central'
inputs:
  NEXUS_MAVEN_REPO:
    default: unused
    required: true
  NEXUS_USERNAME:
    default: unused
    required: true
  NEXUS_PASSWORD:
    default: unused
    required: true
  NEXUS_RELEASE_URL:
    default: unused
    required: true
  NEXUS_SNAPSHOT_URL:
    default: unused
    required: true
  ZEPBEN_GPG_KEY:
    description: "GPG key ID"
    default: unused
    required: true
  MAVEN_CENTRAL_USERNAME:
    description: "Maven Central username"
    default: unused
    required: true
  MAVEN_CENTRAL_PASSWORD:
    description: "Maven Central password"
    default: unused
    required: true
  GPG_KEY_ID:
    description: "Zepben GPG key ID"
    default: unused
    required: true
  GPG_KEY_PASSWORD:
    description: "Zepben GPG key password"
    default: unused
    required: true
  POM_PATH:
    description: "Path to pom.xml"
    required: true
    default: pom.xml
  PROFILE:
    description: "Maven profile"
    required: true
    default: maven-central
  SETTINGS_PATH:
    description: "Path to maven settings.xml"
    required: false

outputs:
  artifact:
    description: "The name of the artifact that is output"
    value: ${{ steps.deploy.outputs.artifact }}
  artifact-path:
    description: "The path to the artifact"
    value: ${{ steps.deploy.outputs.artifact-path }}
  version:
    description: "The version of the arfifact"
    value: ${{ steps.deploy.outputs.version }}
runs:
  using: "composite"
  steps: 
    - name: Cache maven deps
      uses: actions/cache@v4
      with:
        path: /maven
        key: maven
        save-always: true

    - name: Deploy to Maven Central 
      id: deploy
      run: |
        # Use this to fix gpg

 
        echo "Deploying using profile $PROFILE"
        # Run the stuff
        if [ "$PROFILE" = "maven-central" ]
        then
          echo "$ZEPBEN_GPG_KEY" | base64 -d > zepben-gpg.key
          gpg --batch --import zepben-gpg.key

          echo "Update gpg conf"
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          ls ~/.gnupg/gpg.conf

          if [ -z $SETTINGS_PATH ]
          then
            # -B for batch mode to make progress spam go away hopefully
            mvn clean deploy -B -f $POM_PATH -P 'release,maven-central,!zepben-maven' -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dmaven-central.server.username=$MAVEN_CENTRAL_USERNAME -Dmaven-central.server.password=$MAVEN_CENTRAL_PASSWORD -Dgpg.key=$GPG_KEY_ID -Dgpg.password=$GPG_KEY_PASSWORD
          else
            mvn clean deploy -B -f $POM_PATH -P 'release,maven-central,!zepben-maven' -s $SETTINGS_PATH -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dmaven-central.server.username=$MAVEN_CENTRAL_USERNAME -Dmaven-central.server.password=$MAVEN_CENTRAL_PASSWORD -Dgpg.key=$GPG_KEY_ID -Dgpg.password=$GPG_KEY_PASSWORD
          fi
        elif [ "$PROFILE" = "zepben-maven" ]
        then
          if [ -z $SETTINGS_PATH ]
          then
            # -B for batch mode to make progress spam go away hopefully
            mvn clean deploy -B -f $POM_PATH -P 'zepben-maven' -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dserver.release.url=$NEXUS_RELEASE_URL -Dserver.snapshot.url=$NEXUS_SNAPSHOT_URL
          else
            mvn clean deploy -B -f $POM_PATH -P 'zepben-maven' -s $SETTINGS_PATH -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dserver.release.url=$NEXUS_RELEASE_URL -Dserver.snapshot.url=$NEXUS_SNAPSHOT_URL
          fi
        fi
        artifactId=$(xmlstarlet pyx $POM_PATH | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/artifactId")
        version=$(xmlstarlet pyx $POM_PATH | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/version")
        artifact="${artifactId}-${version}.jar"
        artifact_path="$(dirname $POM_PATH)/target/$artifact"
        echo "artifactId: $artifactId"
        echo "version: $version"
        echo "artifact: $artifact"
        echo "artifact-path: $artifact_path"
        echo "artifact=$artifact" >> $GITHUB_OUTPUT
        echo "artifact-path=$artifact_path" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT
      shell: bash
      env:
        NEXUS_MAVEN_REPO: ${{ inputs.NEXUS_MAVEN_REPO }}
        NEXUS_USERNAME: ${{ inputs.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ inputs.NEXUS_PASSWORD }}
        NEXUS_RELEASE_URL: ${{ inputs.NEXUS_RELEASE_URL }}
        NEXUS_SNAPSHOT_URL: ${{ inputs.NEXUS_SNAPSHOT_URL }}
        ZEPBEN_GPG_KEY: ${{ inputs.ZEPBEN_GPG_KEY }}
        MAVEN_CENTRAL_USERNAME: ${{ inputs.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_PASSWORD: ${{ inputs.MAVEN_CENTRAL_PASSWORD }}
        GPG_KEY_ID: ${{ inputs.GPG_KEY_ID }}
        GPG_KEY_PASSWORD: ${{ inputs.GPG_KEY_PASSWORD }}
        POM_PATH: ${{ inputs.POM_PATH }}
        PROFILE: ${{ inputs.PROFILE }}
        SETTINGS_PATH: ${{ inputs.SETTINGS_PATH }}
